openapi: 3.0.1
info:
  title: FA HB Customer API
  description: ''
  version: '1.0'
servers:
  - url: https://api.dev.cstar.pagopa.it/fa/hb/customer
paths:
  /:
    get:
      summary: find
      description: find
      operationId: find
      parameters:
        - name: x-request-id
          in: header
          description: UUID for request identification
          schema:
            type: string
        - name: id
          in: header
          description: UUID for request identification
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResource'
              example:
                fiscalCode: string
                status: string
                activationDate: string
        '401':
          description: ''
        '404':
          description: ''
        '500':
          description: ''
    delete:
      summary: delete
      description: delete
      operationId: delete
      parameters:
        - name: id
          in: header
          description: id univoco che corrisponde al codice fiscale dell'utente
          required: true
          schema:
            type: string
      responses:
        '204':
          description: ''
        '400':
          description: ''
        '409':
          description: ''
        '500':
          description: ''
    put:
      summary: enrollmentCustomerHB
      description: enrollmentcustomerhb
      operationId: enrollmentcustomerhb
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnrollmentCustomerDTOArray'
            example:
              - vatNumber: string
                destinationCode: string
                pec: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResource'
              example:
                fiscalCode: string
                status: string
                activationDate: string
        '401':
          description: ''
        '500':
          description: ''
components:
  schemas:
    EnrollmentCustomerDTOArray:
      type: array
      items:
        $ref: '#/components/schemas/EnrollmentCustomerDTO'
      example:
        - vatNumber: string
          destinationCode: string
          pec: string
    CustomerResource:
      type: object
      properties:
        fiscalCode:
          type: string
        status:
          type: string
        activationDate:
          type: string
        deactivationDate:
          type: string
        vatNumberList:
          type: array
          items:
            type: string
      example:
        fiscalCode: string
        status: string
        activationDate: string
        deactivationDate: string
        vatNumberList:
          - string
    EnrollmentCustomerDTO:
      title: EnrollmentCustomerDTO
      required:
        - vatNumber
      type: object
      properties:
        vatNumber:
          type: string
        destinationCode:
          type: string
        pec:
          type: string
      example:
        vatNumber: string
        destinationCode: string
        pec: string
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]